package io.github.stewartbryson

import groovy.util.logging.Slf4j
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.options.Option

/**
 * A Cacheable Gradle task for publishing Java-based applications as UDFs to Snowflake.
 */
@Slf4j
@CacheableTask
abstract class SnowflakeEphemeralTask extends SnowflakeTask {

    /**
     * When enabled, run using an ephemeral Snowflake database cloned from {@link #database}. Useful with CI/CD testing workflows.
     */
    @Optional
    @Input
    @Option(option = "use-ephemeral", description = "When enabled, run using an ephemeral Snowflake database clone.")
    Boolean useEphemeral = extension.useEphemeral

    /**
     * Optional: specify the ephemeral database name instead of relying on an autogenerated value. The plugin detects CI/CD environments and uses things like PR numbers, branch names, etc. when available.
     */
    @Optional
    @Input
    @Option(option = "ephemeral-name", description = "Optional: specify the ephemeral database name instead of relying on an autogenerated value.")
    String ephemeralName = extension.ephemeralName
}
